### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Jobians** [ArrDev10/WaBot-With-PairingCode#6]
@whiskeysockets/baileys/lib/Socket/socket.js:54
            throw new boom_1.Boom('Connection Closed', { statusCode: Types_1.DisconnectReason.connectionClosed });
                  ^

Error: Connection Closed
    at sendRawMessage (/data/data/com.termux/files/home/php/botawa/backend/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:54:19)
    at sendNode (/data/data/com.termux/files/home/php/botawa/backend/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:73:16)
    at Object.requestPairingCode (/data/data/com.termux/files/home/php/botawa/backend/node_modules/@whiskeysockets/baileys/lib/Socket/socket.js:370:15)
    at async initiateSocket (/data/data/com.termux/files/home/php/botawa/backend/whatsapp/Socket/index.js:62:20)
    at async bot (/data/data/com.termux/files/home/php/botawa/backend/test.js:5:19) {
  data: null,
  isBoom: true,
  isServer: false,
  output: {
    statusCode: 428,
    payload: {
      statusCode: 428,
      error: 'Precondition Required',
      message: 'Connection Closed'
    },
    headers: {}
  }
}

**Comment by Jobians** [comment]
??

**Comment by APdev93** [comment]
sorry bro, im little busy, next i will be fix

**Comment by Jobians** [comment]
So why close
